# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\DBMS\ui\other.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from img_set.img_set import Img_setting
class Ui_MainWindow(Img_setting):
    def setupUi(self, MainWindow):
        # 設置主視窗的基本屬性
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # 創建中央小部件
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # 創建標籤顯示標題
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 50, 800, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setFamily("Microsoft JhengHei")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        
        # 創建表格小部件
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(125, 130, 560, 361))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setFamily("Microsoft JhengHei")
        self.tableWidget.setFont(font)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)  # 設置列數
        self.tableWidget.setRowCount(11)    # 設置行數
        
        
        
        # 設置表格內容唯讀
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        
        # 固定表格大小
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Fixed)

        # 設置表格的行標題
        for i in range(11):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(i, item)
        
        # 設置表格的列標題
        for i in range(3):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setHorizontalHeaderItem(i, item)
        
        # 填充表格內容
        for row in range(11):
            for col in range(3):
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)  # 設置表格內容置中
                self.tableWidget.setItem(row, col, item)
        
        # 設置表格的默認列寬和行高
        self.tableWidget.horizontalHeader().setDefaultSectionSize(191)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        
        # 創建返回主畫面的按鈕
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(355, 520, 102, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet("""
            QPushButton {
                background-color: #444444;
                color: #ffffff;
                border: 3px solid #444444;
                border-radius: 11px;
                padding: 1px;
                font-family: "Microsoft JhengHei";
            }
            QPushButton:hover {
                background-color: #0080FF;
            }
        """)
        
        
        # 設置主視窗的中央小部件
        MainWindow.setCentralWidget(self.centralwidget)
        
        # 創建菜單欄和狀態欄
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # 設置界面文本
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 隱藏視窗邊框
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        
        # 添加 Mac OS 風格的紅橘綠按鈕
        self.button_close = QtWidgets.QPushButton(self.centralwidget)
        self.button_close.setGeometry(QtCore.QRect(10, 10, 15, 15))
        self.button_close.setStyleSheet("""
            QPushButton {
                background-color: #FF605C;
                border: none;
                border-radius: 7px;
            }
            QPushButton:hover {
                background-color: #FF1F1F;
            }
        """)
        self.button_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.button_minimize.setGeometry(QtCore.QRect(30, 10, 15, 15))
        self.button_minimize.setStyleSheet("""
            QPushButton {
                background-color: #FFBD44;
                border: none;
                border-radius: 7px;
            }
            QPushButton:hover {
                background-color: #FFAA00;
            }
        """)
        self.button_maximize = QtWidgets.QPushButton(self.centralwidget)
        self.button_maximize.setGeometry(QtCore.QRect(50, 10, 15, 15))
        self.button_maximize.setStyleSheet("""
            QPushButton {
                background-color: #00CA4E;
                border: none;
                border-radius: 7px;
            }
            QPushButton:hover {
                background-color: #00B324;
            }
        """)
        
        # 連接按鈕的點擊事件
        self.button_close.clicked.connect(MainWindow.close)
        self.button_minimize.clicked.connect(MainWindow.showMinimized)
        self.button_maximize.clicked.connect(MainWindow.showMaximized)
        
        # 設定視窗圓角和背景半透明
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget.setStyleSheet(f"""
            QWidget#centralwidget {{
                background-image: url({self.background_2});
                background-repeat: no-repeat;
                background-position: center;
                border-radius: 15px;
                opacity: 0.25;
            }}
        """)

        # 設定UI文字
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # 設定整體深色主題和圓角按鈕的樣式
        MainWindow.setStyleSheet("""
            QMainWindow {
                background-color: #2b2b2b;
            }
            QLabel {
                color: #ffffff;
            }
            QPushButton {
                background-color: #444444;
                color: #ffffff;
                border: 2px solid #444444;
                border-radius: 15px;
                padding: 3px;
                font-family: "Microsoft JhengHei";
            }
            QPushButton:hover {
                background-color: #0080FF;
            }
        """)

        # 添加圓角樣式
        self.tableWidget.setStyleSheet("""
            QTableWidget {
                border: 5px solid #444444;
                background-color: #2E2E2E;
                color: #FFFFFF;
            }
            QTableWidget::item {
                background-color: #3C3C3C;
                color: #FFFFFF;
            }
            QTableWidget::item:selected {
                background-color: #0080FF;
                color: #FFFFFF;
            }
            QHeaderView::section {
                background-color: #444444;
                color: #FFFFFF;
            }
            QScrollBar:vertical {
                border: none;
                background: #444444; /* 滾動條背景顏色 */
                width: 10px; /* 滾動條寬度 */
                margin: 22px 0 22px 0; /* 上下邊距 */
            }
            QScrollBar::handle:vertical {
                background: #ADADAD; /* 滾動條滑塊顏色 */
                min-height: 20px; /* 滑塊最小高度 */
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                background: none; /* 隱藏上下箭頭 */
            }
            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
                background: none; /* 隱藏滾動條的頁面 */
            }
            QScrollBar:horizontal {
                border: none;
                background: #444444; /* 滾動條背景顏色 */
                height: 10px; /* 滾動條高度 */
                margin: 0 22px 0 22px; /* 左右邊距 */
            }
            QScrollBar::handle:horizontal {
                background: #ADADAD; /* 滾動條滑塊顏色 */
                min-width: 20px; /* 滑塊最小寬度 */
            }
            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
                background: none; /* 隱藏左右箭頭 */
            }
            QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {
                background: none; /* 隱藏滾動條的頁面 */
            }
        """)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "其他監理站"))
        self.label_4.setStyleSheet("""
            QLabel {
                color: #000000;
                font-weight: bold;
                font-size: 40px;
            }
        """)
        self.tableWidget.setSortingEnabled(False)
        
        # 設置表格的列標題
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所站名稱"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "地址"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "電話"))
        
        # 填充表格的內容
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        data = [
            ("臺北市區監理所", "臺北市松山區八德路四段21號", "02-27630155"),
            ("士林監理站", "臺北市士林區承德路五段80號", "02-28314155"),
            ("基隆監理站", "基隆市七堵區實踐路296號", "02-24515311"),
            ("連江監理站", "連江縣南竿鄉津沙村155號", "0836-22694"),
            ("金門監理站", "金門縣金湖鎮黃海路六之一號", "082-332407"),
            ("臺北區監理所", "新北市樹林區中正路248巷7號", "02-26884366"),
            ("蘆洲監理站", "新北市蘆洲區中山二路163號", "02-22886883"),
            ("板橋監理站", "新北市中和區中山路三段116號", "02-22227835"),
            ("宜蘭監理站", "宜蘭縣五結鄉中正路二段9號", "03-9658461"),
            ("花蓮監理站", "花蓮縣吉安鄉中正路二段152號", "03-8523166"),
            ("玉里監理分站", "花蓮縣玉里鎮中華路427號", "03-8883161")
        ]
        for row, (name, address, phone) in enumerate(data):
            self.tableWidget.item(row, 0).setText(_translate("MainWindow", name))
            self.tableWidget.item(row, 1).setText(_translate("MainWindow", address))
            self.tableWidget.item(row, 2).setText(_translate("MainWindow", phone))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        
        # 設置返回按鈕的文本
        self.pushButton_6.setText(_translate("MainWindow", "返回主畫面"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
